# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 300)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_first = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_first.setObjectName("lineEdit_first")
        self.horizontalLayout.addWidget(self.lineEdit_first)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_second = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_second.setObjectName("lineEdit_second")
        self.horizontalLayout_2.addWidget(self.lineEdit_second)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_button = QtWidgets.QPushButton(parent=Form)
        self.add_button.setEnabled(True)
        self.add_button.setObjectName("add_button")
        self.add_button.clicked.connect(self.add)
        self.horizontalLayout_3.addWidget(self.add_button)
        self.minus_button = QtWidgets.QPushButton(parent=Form)
        self.minus_button.setObjectName("minus_button")
        self.minus_button.clicked.connect(self.minus)
        self.horizontalLayout_3.addWidget(self.minus_button)
        self.multiple_button = QtWidgets.QPushButton(parent=Form)
        self.multiple_button.setObjectName("multiple_button")
        self.multiple_button.clicked.connect(self.multiply)
        self.horizontalLayout_3.addWidget(self.multiple_button)
        self.divide_button = QtWidgets.QPushButton(parent=Form)
        self.divide_button.setObjectName("divide_button")
        self.divide_button.clicked.connect(self.divide)
        self.horizontalLayout_3.addWidget(self.divide_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_result = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(18)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("QLabel {\n"
"color:green\n"
"}")
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def add(self):
        fNumber = int(self.lineEdit_first.text())
        sNumber = int(self.lineEdit_second.text())
        result = fNumber + sNumber
        self.label_result.setText("Addition: {}".format(result))

    def minus(self):
        fNumber = int(self.lineEdit_first.text())
        sNumber = int(self.lineEdit_second.text())
        result = fNumber - sNumber
        self.label_result.setText("Minus: {}".format(result))

    def multiply(self):
        fNumber = int(self.lineEdit_first.text())
        sNumber = int(self.lineEdit_second.text())
        result = fNumber * sNumber
        self.label_result.setText("Multiple: {}".format(result))

    def divide(self):
        fNumber = int(self.lineEdit_first.text())
        sNumber = int(self.lineEdit_second.text())
        result = fNumber / sNumber
        self.label_result.setText("Divide: {}".format(result))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "First Number"))
        self.lineEdit_first.setPlaceholderText(_translate("Form", "Please Enter First Number"))
        self.label_2.setText(_translate("Form", "Second Number"))
        self.lineEdit_second.setPlaceholderText(_translate("Form", "Please Enter Second Number"))
        self.add_button.setText(_translate("Form", "+"))
        self.minus_button.setText(_translate("Form", "-"))
        self.multiple_button.setText(_translate("Form", "*"))
        self.divide_button.setText(_translate("Form", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
