# Form implementation generated from reading ui file 'CalendarDemo.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(908, 616)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_date = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")
        self.horizontalLayout.addWidget(self.label_date)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=Form)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout.addWidget(self.calendarWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_days = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_days.setFont(font)
        self.label_days.setObjectName("label_days")
        self.horizontalLayout_2.addWidget(self.label_days)
        self.spinBox = QtWidgets.QSpinBox(parent=Form)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.calculate)

        self.verticalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_reservation = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_reservation.setFont(font)
        self.label_reservation.setText("")
        self.label_reservation.setObjectName("label_reservation")
        self.verticalLayout.addWidget(self.label_reservation)
        self.label_result = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def calculate(self):
        roomRent = 40
        dateSelected = self.calendarWidget.selectedDate()
        dateInString = str(dateSelected.toPyDate())
        numDays = self.spinBox.value()

        self.label_reservation.setText("Date of Reservation {} , Number of Days {} ".format(dateInString, numDays))
        total = roomRent * numDays
        self.label_result.setText("Room rent for single day {} , Total Amount {} ".format(roomRent, total))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_date.setText(_translate("Form", "Date of Reservation:"))
        self.label_days.setText(_translate("Form", "Number of Days:"))
        self.pushButton.setText(_translate("Form", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
