# Form implementation generated from reading ui file 'ListWidgetApp.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog, QInputDialog, QLineEdit, QMessageBox


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(682, 515)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(parent=Dialog)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_add = QtWidgets.QPushButton(parent=Dialog)
        self.button_add.setObjectName("button_add")

        self.button_add.clicked.connect(self.add_item)

        self.verticalLayout.addWidget(self.button_add)
        self.button_edit = QtWidgets.QPushButton(parent=Dialog)
        self.button_edit.setObjectName("button_edit")

        self.button_edit.clicked.connect(self.edit_item)

        self.verticalLayout.addWidget(self.button_edit)
        self.button_remove = QtWidgets.QPushButton(parent=Dialog)
        self.button_remove.setObjectName("button_remove")

        self.button_remove.clicked.connect(self.remove_item)

        self.verticalLayout.addWidget(self.button_remove)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.button_sort = QtWidgets.QPushButton(parent=Dialog)
        self.button_sort.setObjectName("button_sort")

        self.button_sort.clicked.connect(self.sort_item)

        self.verticalLayout.addWidget(self.button_sort)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def add_item(self):
        row = self.listWidget.currentRow()
        title = "Add Item"
        data, ok = QInputDialog.getText(self, title, title)

        if ok and data is not None:
            self.listWidget.insertItem(row, data)

    def edit_item(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)

        if item is not None:
            title = "Edit Item"
            data, ok = QInputDialog.getText(self, title, title, QLineEdit.EchoMode.Normal, item.text())
            if ok and data is not None:
                item.setText(data)

    def remove_item(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)

        if item is None:
            return
        reply = QMessageBox.question(self, "Remove Item", "Do you want to remove item ? ",
                                     QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No)

        if reply == QMessageBox.StandardButton.Yes:
            self.listWidget.takeItem(row)

    def sort_item(self):
        self.listWidget.sortItems()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button_add.setText(_translate("Dialog", "Add"))
        self.button_edit.setText(_translate("Dialog", "Edit"))
        self.button_remove.setText(_translate("Dialog", "Remove"))
        self.button_sort.setText(_translate("Dialog", "Sort"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
